version: '3.8'

services:
  web:
    image: hannainstruments/shopware-web:6.6.7.0
    container_name: shopware_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./shopware-files:/var/www/html
    environment:
      - PHP_VERSION=8.2
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - database
    networks:
      - shopware
    restart: unless-stopped

  database:
    image: hannainstruments/shopware-database:6.6.7.0
    container_name: shopware_database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shopware
    restart: unless-stopped

volumes:
  db_data:

networks:
  shopware:
    driver: bridge
