version: "3.8"

services:
  web:
    image: ghcr.io/newsenses/hanna-instruments-shopware-deployment/web:${IMAGE_TAG}
    description: "Shopware 6.6.7.0 Web Server"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - PHP_VERSION=8.2
      - COMPOSER_MEMORY_LIMIT=-1
      - DATABASE_URL=mysql://{{ .Env.MYSQL_USER }}:{{ .Env.MYSQL_PASSWORD }}@database:3306/{{ .Env.MYSQL_DATABASE }}
      - APP_SECRET={{ .Env.SHOPWARE_SECRET }}
      - APP_ENV=prod
      - LOCK_DSN=flock
      - SHOPWARE_STORE_SKIP_DOMAIN_VALIDATION=true
    volumes:
      - "shopware-files:/var/www/html"
    depends_on:
      - "database"

  database:
    image: ghcr.io/newsenses/hanna-instruments-shopware-deployment/database:${IMAGE_TAG}
    description: "Shopware Database"
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={{ .Env.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE={{ .Env.MYSQL_DATABASE }}
      - MYSQL_USER={{ .Env.MYSQL_USER }}
      - MYSQL_PASSWORD={{ .Env.MYSQL_PASSWORD }}
    volumes:
      - "db-data:/var/lib/mysql"

volumes:
  shopware-files:
    name: shopware-files-volume
  db-data:
    name: shopware-db-volume
