name: Deploy Shopware to Mittwald

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      actions: read

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: "shopware"
      MYSQL_USER: "shopware"
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SHOPWARE_SECRET: ${{ secrets.SHOPWARE_SECRET }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push Web Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: ghcr.io/${{ github.repository }}/web:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build & Push Database Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.database
          push: true
          tags: ghcr.io/${{ github.repository }}/database:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Replace IMAGE_TAG in stack.yaml
        run: |
          sed -i "s/\${IMAGE_TAG}/${{ github.sha }}/g" "${{ github.workspace }}/mittwald-stack.yaml"
          cat "${{ github.workspace }}/mittwald-stack.yaml"

      - name: Deploy to Mittwald
        uses: mittwald/deploy-container-action@v1.0.1
        with:
          api_token: ${{ secrets.MITTWALD_API_TOKEN }}
          stack_id: "e26a6f4e-8bd2-422f-b41b-d8bce088cf85"
          stack_file: "${{ github.workspace }}/mittwald-stack.yaml"
          skip_recreation: "database"
